flowchart LR
  %%{ init: { 'flowchart': { 'curve': 'linear' } } }%%

  subgraph content [ ]
    %% Content
    Eins(fa:fa-home Eins<br/>/sites/TestEins):::CommSite
 Zwei(fa:fa-home Zwei<br/>/sites/TestZwei):::CommSite

    
    %% Relations
    
  end

  subgraph legend [ ]
    CommSite(Communication Site):::CommSite
    TeamSite[Team Site]:::TeamSite
    SPOTeamSite>Team Site w/o M365 Group]:::SPOTeamSite
  end

  %% Style definitions
  classDef default fill:white, stroke:black, stroke-width:0.5px;
  classDef CommSite fill:yellow;
  classDef TeamSite fill:white;
  classDef cluster fill:#fff,stroke:#bbb,stroke-width:0px,color:#326ce5;
  classDef legend fill:#fff,stroke:#bbb,stroke-width:1px,color:black,font-size:10px;

  class content cluster;
  class legend legend;